### ISSUE TITLE
Enhancement : Get Altitude

### ISSUE THREAD

**Issue by tfagart** [cryxy/my-owntracks-recorder#4]
Hello,

Thank's a lot for your software. I was wondering wether you think your going to add the altitude to the collected data.

It seems it is available in the MQTT.

owntracks/test/AAAAAAAAAAAAAAA {"_type":"location","acc":4,"**alt**":860,"batt":42,"bs":1,"cog":9,"conn":"m","lat":42.629982,"lon":-0.327211,"p":91.411,"tid":"6E","tst":1636898803,"vac":4,"vel":51}

**Comment by cryxy** [comment]
Hi!

The altitude is already included in the collected data.  Isn't it working for you?

```		
      if (dto.getAlt() != null) {
			pointBuilder.addField(FIELD_ALT, dto.getAlt());
```

**Comment by tfagart** [comment]
Hello,

Thanks for your answer.
The only field I got in InfluxDB are the following

> select * from locations
name: locations
time                accuracy battLevel connectivity country deviceName                           geoHash lat       lon       placename                            tid userName
----                -------- --------- ------------ ------- ----------                           ------- ---       ---       ---------                            --- --------

Altitude seems to be missing.

Regards

Thomas

**Comment by tfagart** [comment]
Hello,

It seems this is ok now with release 1.1.0.

Thanx

Thomas
