### ISSUE TITLE
Request Failed when using the API

### ISSUE THREAD

**Issue by tfagart** [cryxy/my-owntracks-recorder#5]
Hello,

I've tried to used the API that allow GPX export.

I got 500 response (Request Failed)

<html><head><title>Grizzly 2.4.0</title><style></style> </head><body><div class="header">Request failed.</div><div class="body">Request failed.</div><div class="footer">Grizzly 2.4.0</div></body></html>

The authentication seems to be ok though.

I've tried to debug further, but I don't know what to do.

Thanx

Thomas

**Comment by cryxy** [comment]
Unfortunately, the API currently only works with Java 8. I plan to rewrite it. I updated the docker image to use java 8: 
`docker pull cryxy/my-owntracks-recorder:1.1.1-snapshot`

**Comment by tfagart** [comment]
Ok many thanx, with the new docker image, it is working properly.
